version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: claude-memory-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port (optional)
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped
    networks:
      - memory-net

  # Optional: Qdrant Web UI for debugging
  # Note: The official web UI is built into Qdrant itself at :6333
  # Commenting out separate UI container as it's not needed
  # qdrant-ui:
  #   image: qdrant/qdrant-web-ui:latest
  #   container_name: claude-memory-qdrant-ui
  #   ports:
  #     - "6335:6335"
  #   environment:
  #     - QDRANT_URL=http://qdrant:6333
  #   depends_on:
  #     - qdrant
  #   networks:
  #     - memory-net

networks:
  memory-net:
    driver: bridge