apiVersion: v2
name: memory-mcp
description: A Helm chart for Claude Memory MCP System
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
- memory
- mcp
- claude
- ai
- vector-database
- embeddings
home: https://github.com/your-org/claude-memory-mcp
sources:
- https://github.com/your-org/claude-memory-mcp
maintainers:
- name: Memory MCP Team
  email: team@your-org.com
dependencies:
- name: qdrant
  version: "0.1.0"
  repository: "https://qdrant.github.io/qdrant-helm"
  condition: qdrant.enabled
- name: prometheus
  version: "25.0.0"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: monitoring.prometheus.enabled
- name: grafana
  version: "7.0.0"
  repository: "https://grafana.github.io/helm-charts"
  condition: monitoring.grafana.enabled